bpx/mirrorme:
  model_name: "bpx_flat_45.pt"

  kp: 40.0
  kd: 1.0

  action_scale: 0.25

  clip_obs: 100.0
  clip_actions: 100.0

  ang_vel_scale: 0.25
  dof_vel_scale: 0.05

  commands_scale: [2.0, 2.0, 0.25]